### ISSUE TITLE
Pyhton problem

### ISSUE THREAD

**Issue by thecorax** [defaultnamehere/zzzzz#10]
With python2.7:

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Got error from request, restarting...

```

python3:

```
Traceback (most recent call last):
  File "fetcher.py", line 6, in <module>
    import requests
ImportError: No module named requests

```

Yes, I read the page recommended for python2.7. No, I am not not able to fix it with the recommended solutions. 
Yes, I ran all that "pip install requests" etc, and the rest you can find here.

using my raspberry 2 with debian.

edit:

got a little further with: sudo apt-get install python3-requests

```
Traceback (most recent call last):
  File "fetcher.py", line 194, in <module>
    f.start_request()
  File "fetcher.py", line 110, in start_request
    resp = self.make_request()
  File "fetcher.py", line 52, in make_request
    raw_response = response_obj.text
  File "/usr/lib/python3/dist-packages/requests/models.py", line 831, in text
    content = str(self.content, encoding, errors='replace')
TypeError: str() argument 2 must be str, not None
```

**Comment by thecorax** [comment]
If you have the same problem you probably didn't enter the correct cookie/ client_id.

**Comment by logicabrity** [comment]
Speaking of cookie, how do I find it? The uid and client_id was easy to find as described in the README.

**Comment by zeusk** [comment]
@thecorax select the request to /pull and then select the Headers tab, inspect the response headers for the cookie.
