### ISSUE TITLE
Crash Unexpectedly Again

### ISSUE THREAD

**Issue by tkgmomosheep** [defaultnamehere/zzzzz#44]
The code below showed up
`Traceback (most recent call last):
  File "fetcher.py", line 179, in <module>
    f.start_request()
  File "fetcher.py", line 95, in start_request
    resp = self.make_request()
  File "fetcher.py", line 69, in make_request
    print("Response:" + str(data))
  File "C:\Users\TKGMoMoSheep\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u6bdb' in position 1413: character maps to <undefined>`

**Comment by AtariDHD** [comment]
I had the same issue.  I opened FB and used the new client id in secrets.txt.  Started working again.
